### ISSUE TITLE
questions about using

### ISSUE THREAD

**Issue by PetePro** [RagnarDa/dumbmutate#1]
1. what testing frameworks can be used with ‘dumbmutate’? 
2. Is there a more detailed example? Or Can you explain the meaning of each parameter in detail?
Thank you!

**Comment by RagnarDa** [comment]
Hi! Glad you found it!

1) You can use it with any testing framework or none at all. Only requirement is that if the tests succeed it should return a zero and if any tests fails it should return non-zero. Most, if not all, testing framework do this.

2) The program works by changing something in your source code (mutate), then build it (using a command you provide it) and then run it and see if the tests pass (they shouldn’t). It can only work with one file at a time. Say your program contains a file that is called CustomerHandling.cpp. First you should make sure you have 100% or near 100% code coverage of that file. Then you define that file as the one we will mutate with parameter “—file=CustomerHandling.cpp“. Then you need to provide a command to build/compile your program, usually “make” or “cmake —build ./“. Then you need to provide how to test the program (provided it was able to build it). You do this with —test parameter, so if your program is called “MyApp” then it’s “—test=./MyApp”. So something like this:

dumbmutate --file=CustomerHandling.cpp --compile=make --test=./MyApp

You should consider using the Unix timeout command as showed in the ReadMe and also maybe using a RAM-drive since it will be many writes to the hardrive.

Hope that helps!

**Comment by RagnarDa** [comment]
The commands for compile and test are just commands as if written in the terminal if that’s not clear. It could for example be “sh compilemycode.sh” or “runtests.bat”

**Comment by PetePro** [comment]
Thank you for your responding and I have succeeded in using this tool. 

When I use it on an addition function, if it mutate '+' to '-', the tests should be failed, which means the mutation should be killed. 
However the results is `survived`: 

```
Original:
5:      case '+':
Mutation:
5:      case '-':
Compiling...
make: 'external/gtest/gtest-all.o' is up to date.
Testing...
[==========] Running 3 tests from 1 test suites.
[----------] Global test environment set-up.
[----------] 3 tests from FunctionsTest
[ RUN      ] FunctionsTest.calculator1
SetUp FunctionsTest
TearDown FunctionsTest
[       OK ] FunctionsTest.calculator1 (16 ms)
[ RUN      ] FunctionsTest.calculator2
SetUp FunctionsTest
TearDown FunctionsTest
[       OK ] FunctionsTest.calculator2 (14 ms)
[ RUN      ] FunctionsTest.accumulator
SetUp FunctionsTest
TearDown FunctionsTest
[       OK ] FunctionsTest.accumulator (41 ms)
[----------] 3 tests from FunctionsTest (113 ms total)
[----------] Global test environment tear-down
[==========] 3 tests from 1 test suites ran. (208 ms total)
[  PASSED  ] 3 tests.
Survived.
```

The testing framework I use is GoogleTest, and the test code is:
```
TEST_F(FunctionsTest,calculator1) {
	int res = f.calculator(2, 2, '+');
	ASSERT_EQ(res, 4);
}
```

I want to know if there are any precautions that need attention?

**Comment by PetePro** [comment]
Thank you for your responding and I have succeeded in using this tool. 

When I use it on an addition function, if it mutate '+' to '-', the tests should be failed, which means the mutation should be killed. 
However the results is `survived`: 

```
Original:
5:      case '+':
Mutation:
5:      case '-':
Compiling...
make: 'external/gtest/gtest-all.o' is up to date.
Testing...
[==========] Running 3 tests from 1 test suites.
[----------] Global test environment set-up.
[----------] 3 tests from FunctionsTest
[ RUN      ] FunctionsTest.calculator1
SetUp FunctionsTest
TearDown FunctionsTest
[       OK ] FunctionsTest.calculator1 (16 ms)
[ RUN      ] FunctionsTest.calculator2
SetUp FunctionsTest
TearDown FunctionsTest
[       OK ] FunctionsTest.calculator2 (14 ms)
[ RUN      ] FunctionsTest.accumulator
SetUp FunctionsTest
TearDown FunctionsTest
[       OK ] FunctionsTest.accumulator (41 ms)
[----------] 3 tests from FunctionsTest (113 ms total)
[----------] Global test environment tear-down
[==========] 3 tests from 1 test suites ran. (208 ms total)
[  PASSED  ] 3 tests.
Survived.
```

The testing framework I use is GoogleTest, and the test code is:
```
TEST_F(FunctionsTest,calculator1) {
	int res = f.calculator(2, 2, '+');
	ASSERT_EQ(res, 4);
}
```

I want to know if there are any precautions that need attention?

**Comment by RagnarDa** [comment]
First, I would try to see if there is something funky with that switch in calculator(). Try something like this:
TEST_F(FunctionsTest,calculator1) {
	int res = f.calculator(2, 2, '+');
	ASSERT_EQ(res, 4);

        res = f.calculator(2, 2, '-');
	ASSERT_EQ(res, 0);
}

There might be some fall through in the switch or something similar. 

I would also try changing the the plus on line 5 to a minus manually and see if the test failed then. Has dumbmutate permission to write to the file? Is it mutating the right file?

**Comment by RagnarDa** [comment]
Hey, this looks suspicious:

Compiling...
make: 'external/gtest/gtest-all.o' is up to date.

I would have expected something like “Built: myprogram”. Check that you are providing the right build command, and not trying to build some other project.

**Comment by PetePro** [comment]
Thank you for your suggestions, I will check my program.
